# -*- mode: python ; coding: utf-8 -*-
"""
Internal Regulations Finder - lite console build

Build:
    pyinstaller regulation_search_lite.spec

Consistency notes:
    2026-03-16 - explicit parser hiddenimports added for HWP/HWPX extraction path
"""

import os

block_cipher = None
project_dir = os.path.dirname(os.path.abspath(SPEC))

datas = [
    (os.path.join(project_dir, "templates"), "templates"),
    (os.path.join(project_dir, "static"), "static"),
]

settings_example = os.path.join(project_dir, "config", "settings.example.json")
if os.path.exists(settings_example):
    datas.append((settings_example, "config"))

hiddenimports = [
    "flask",
    "flask.json",
    "flask.json.provider",
    "flask_cors",
    "flask_compress",
    "werkzeug",
    "werkzeug.serving",
    "jinja2",
    "markupsafe",
    "waitress",
    "waitress.server",
    "sqlite3",
    "threading",
    "queue",
    "concurrent.futures",
    "docx",
    "pypdf",
    "openpyxl",
    "olefile",
    "lxml",
    "lxml.etree",
    "psutil",
    "encodings.utf_8",
    "encodings.cp949",
    "encodings.euc_kr",
    "app",
    "app.config",
    "app.utils",
    "app.routes",
    "app.routes.main_routes",
    "app.routes.api_search",
    "app.routes.api_files",
    "app.routes.api_system",
    "app.services",
    "app.services.search",
    "app.services.document",
    "app.services.db",
    "app.services.parsers",
    "app.services.parsers.hwp_adapter",
    "app.services.parsers.hwpx_adapter",
    "app.services.parsers.hwp_models",
]

excludes = [
    "torch",
    "torchvision",
    "torchaudio",
    "tensorflow",
    "keras",
    "tensorboard",
    "transformers",
    "huggingface_hub",
    "sentence_transformers",
    "langchain",
    "langchain_core",
    "langchain_community",
    "langchain_text_splitters",
    "langchain_huggingface",
    "faiss",
    "faiss_cpu",
    "accelerate",
    "safetensors",
    "tokenizers",
    "optimum",
    "onnx",
    "onnxruntime",
    "tkinter",
    "tk",
    "_tkinter",
    "PyQt5",
    "PyQt6",
    "PySide2",
    "PySide6",
    "wx",
    "wxPython",
    "matplotlib",
    "pandas",
    "scipy",
    "seaborn",
    "plotly",
    "bokeh",
    "numpy.testing",
    "IPython",
    "notebook",
    "jupyter",
    "pytest",
    "unittest",
    "cv2",
    "opencv",
    "PIL.ImageTk",
    "pytesseract",
    "pdf2image",
    "imageio",
    "moviepy",
    "scrapy",
    "selenium",
    "requests_html",
    "email.test",
    "test",
    "tests",
    "lib2to3",
    "sympy",
    "numba",
    "numexpr",
]

a = Analysis(
    ["run.py"],
    pathex=[project_dir],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

excluded_binaries = [
    "torch",
    "libtorch",
    "c10",
    "caffe2",
    "torch_cpu",
    "torch_cuda",
    "libc10",
    "libc10_cuda",
    "libshm",
    "libnvfuser",
    "fbgemm",
    "asmjit",
    "dnnl",
    "ideep",
    "cuda",
    "cudnn",
    "cublas",
    "cufft",
    "cusparse",
    "curand",
    "nvcuda",
    "nvrtc",
    "nvidia",
    "nvjitlink",
    "cudart",
    "cublaslt",
    "cusolver",
    "mkl_",
    "mkl-",
    "libmkl",
    "libiomp",
    "libiomk",
    "svml",
    "libimalloc",
    "tbb",
    "libtbb",
    "openblas",
    "libopenblas",
    "qt5",
    "qt6",
    "pyqt",
    "pyside",
    "libqt",
    "Qt5",
    "Qt6",
    "tensorflow",
    "libtensorflow",
    "opencv",
    "cv2",
    "libopencv",
    "llvm",
    "clang",
    "libllvm",
    "libclang",
    "transformers",
    "tokenizers",
    "sentencepiece",
    "triton",
    "nvtx",
    "magma",
    ".pdb",
    "_d.dll",
    "_d.pyd",
]
a.binaries = [b for b in a.binaries if not any(token in b[0].lower() for token in excluded_binaries)]

excluded_datas = [
    "tcl",
    "tk",
    "matplotlib",
    "mpl-data",
    "torch",
    "transformers",
    "huggingface",
    "sentence_transformers",
    "faiss",
    "share/jupyter",
    "share/doc",
    "include/",
    ".dist-info",
    "__pycache__",
    "tests/",
    "test/",
]
a.datas = [d for d in a.datas if not any(token in d[0].lower() for token in excluded_datas)]

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="사내규정검색기",
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=True,
    upx=True,
    upx_exclude=[
        "vcruntime140.dll",
        "python3*.dll",
        "msvcp*.dll",
        "api-ms-*.dll",
        "ucrtbase.dll",
    ],
    name="사내규정검색기",
)
